#!/bin/bash

#Check connection to all remote peers and forbid receiving any commits
#Exit 1 if connection lost, else exit 0

DOWN="State: Peer in Cluster (Disconnected)"

#There might me some user access issues with this part: possible solutions are su- or ssh as another user
STATUS=$(sudo gluster peer status | grep "$DOWN" -m 1)

if [[ $STATUS == "$DOWN" ]]; then
	echo "Connection with on of the replication storages could not be established"
	echo "Updating the repository is denied until the connection issue has been resolved"
	exit 1
else
	exit 0
fi
